name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm # automatic pnpm store caching

      - run: corepack enable # makes the repo-pinned pnpm available
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build
      - run: pnpm test
