name: Release

on:
  workflow_run:
    workflows: ["CI"] # keep the name identical to ci.yml
    branches: [main]
    types: [completed]

jobs:
  publish-and-tag:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing tags
      packages: write # optional (GH Packages)

    steps:
      - uses: actions/checkout@v4

      # Install pnpm first
      - uses: pnpm/action-setup@v3
        with:
          version: 10.10.0
          run_install: false

      # Then set up Node with pnpm caching
      - name: Set up Node 20 + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          registry-url: "https://registry.npmjs.org/"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build

      - name: Publish via Changesets
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec changeset publish

      - name: Tag git with published version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(jq -r '.version' packages/cli/package.json)
          git config user.name  'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git tag "v$version"
          git push --tags
