name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write # version PR + tags
      pull-requests: write
      packages: write # needed if you ever publish to GH Packages

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10.10.0
          run_install: false

      - name: Set up Node 20 + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          registry-url: "https://registry.npmjs.org/"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - run: pnpm install --frozen-lockfile # install once for all steps

      - name: Build CLI + copy templates
        run: pnpm -r run build

      - name: Release with Changesets
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
